name: terramerge-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - pyarrow
  - hydra-core
  - loguru
  - ruamel.yaml
  - geometrie
  - geopandas
  - gdal
  - tqdm
  - duckdb
  - h3<4.0
  - pip:
      - imbalanced-learn

  # conda env create -f environment.yml