stage: model
stages:
  # jeśli selekcję cech robisz tutaj, dorzuć: select_features
  - train_model

inputs:
  features_selected: ${contracts.features_selected_file}
outputs:
  model_dir: ${contracts.model_dir}
  model_file: ${contracts.model_file}

cv:
  type: GroupKFold
  n_splits: 5
  group_col: hex_cell

logging:
  summary: ${hydra:run.dir}/train_summary.json
